import json
import boto3
import urllib3

# Initialize clients
secretsmanager = boto3.client('secretsmanager', region_name='ap-south-2')
http = urllib3.PoolManager()

# Cache for GitHub token
_github_token = None

def get_github_token():
    """Get GitHub token from Secrets Manager with caching"""
    global _github_token
    
    if _github_token:
        return _github_token
    
    try:
        response = secretsmanager.get_secret_value(SecretId='CodeReview/GitHubToken')
        secret_dict = json.loads(response['SecretString'])
        _github_token = secret_dict.get('GITHUB_TOKEN')
        print("✅ Retrieved GitHub token from Secrets Manager")
        return _github_token
    except Exception as e:
        print(f"❌ Error retrieving GitHub token: {str(e)}")
        raise

def lambda_handler(event, context):
    """Post AI code review as PR comment"""
    
    print("=" * 60)
    print("💬 GITHUB COMMENT POSTER")
    print("=" * 60)
    
    try:
        # Get aggregated review
        aggregation_result = event.get('aggregation_result', {})
        aggregated_review = aggregation_result.get('combined_review', '')
        pr_number = event.get('pr_number')
        repo_name = event.get('repo_name')
        
        if not all([aggregated_review, pr_number, repo_name]):
            return {
                "statusCode": 400,
                "error": True,
                "message": "Missing required fields: aggregated_review, pr_number, or repo_name"
            }
        
        print(f"📝 Posting review to PR #{pr_number} in {repo_name}")
        
        # Get GitHub token
        token = get_github_token()
        
        # Prepare comment body
        comment_body = f"""## 🤖 AI Code Review

{aggregated_review}

---
*Generated by AI Code Review Platform powered by Google Gemini 2.5 Flash*
*Cost: $0.00 (FREE!) 🎉*
"""
        
        # Post comment to GitHub
        url = f"https://api.github.com/repos/{repo_name}/issues/{pr_number}/comments"
        
        headers = {
            'Authorization': f'token {token}',
            'Accept': 'application/vnd.github.v3+json',
            'User-Agent': 'AI-Code-Review-Platform'
        }
        
        payload = json.dumps({
            'body': comment_body
        })
        
        response = http.request(
            'POST',
            url,
            body=payload,
            headers=headers
        )
        
        if response.status == 201:
            response_data = json.loads(response.data.decode('utf-8'))
            comment_url = response_data.get('html_url')
            
            print(f"✅ Comment posted successfully!")
            print(f"🔗 Comment URL: {comment_url}")
            
            return {
                "statusCode": 200,
                "message": "Comment posted successfully",
                "comment_url": comment_url,
                "pr_number": pr_number,
                "repo_name": repo_name
            }
        else:
            error_msg = response.data.decode('utf-8')
            print(f"❌ Failed to post comment: {response.status}")
            print(f"Error: {error_msg}")
            
            return {
                "statusCode": response.status,
                "error": True,
                "message": f"GitHub API error: {error_msg}"
            }
        
    except Exception as e:
        print(f"❌ Error posting comment: {str(e)}")
        import traceback
        print(traceback.format_exc())
        
        return {
            "statusCode": 500,
            "error": True,
            "message": str(e)
        }